#!/usr/bin/env python
# encoding: utf-8
# Copyright (c) 2013-2018 GomSpace A/S. All rights reserved.

import os
import gs_gcc
import gs_util

APPNAME = 'gatoss_uc_client'


def options(ctx):
    ctx.load('gs_gcc')
    ctx.recurse(gs_gcc.get_modules(ctx))

    gr = ctx.add_option_group('ADS-B client options')
    gr.add_option('--with-task-passive', action='store_true', help='Select if task passive should be included')


def configure(ctx):
    ctx.load('gs_gcc')
    ctx.recurse(gs_gcc.get_modules(ctx))

    ctx.env.append_unique('USES_GATOSS_CLIENT', ['gscsp', 'gosh', 'util', 'embed', 'param_client'])

    ctx.env.append_unique('FILES_GATOSS_CLIENT', ['src/*.c', 'src/param/*.c'])

    ctx.define_cond('TASK_PASSIVE', ctx.options.with_task_passive)
    ctx.write_config_header('include/conf_adsb_client.h', top=True, remove=True)


def build(ctx):
    ctx.recurse(gs_gcc.get_modules(ctx))

    public_include = APPNAME + '_h'
    ctx(export_includes=['include'], name=public_include)

    ctx.gs_call_handler(handler='param_gen_4_3', name=APPNAME, prefix='adsb',
                        generate_host=True, generate_client=True, generate_rsti=True, generate_addr=False)

    ctx.gs_objects(source=ctx.path.ant_glob(ctx.env.FILES_GATOSS_CLIENT),
                   target=APPNAME,
                   use=ctx.env.USES_GATOSS_CLIENT + [public_include])

    ctx.gs_shlib(source=ctx.path.ant_glob(ctx.env.FILES_GATOSS_CLIENT),
                 target=APPNAME,
                 gs_use_shlib=ctx.env.USES_GATOSS_CLIENT + [public_include])

    ctx.gs_python_bindings(source=ctx.path.ant_glob('bindings/python/*.c'),
                           target=APPNAME,
                           gs_use_shlib=ctx.env.USES_GATOSS_CLIENT + [APPNAME],
                           package='libgsgatoss_uc_client')


def gs_dist(ctx):
    ctx.set_appname(APPNAME)
    ctx.add_default_files(source_module=True)
