#!/usr/bin/env python
# encoding: utf-8
# Copyright (c) 2013-2017 GomSpace A/S. All rights reserved.

import os
import gs_gcc
import gs_doc
import gs_dist

APPNAME = 'ftp'


def options(ctx):
    ctx.load('gs_gcc gs_doc')
    gs_gcc.gs_recurse(ctx)

    gr = ctx.add_option_group('libftp options')
    gr.add_option('--ftp-disable-glob', action='store_true', help='Disable use of glob in backend file')


def configure(ctx):
    ctx.load('gs_gcc gs_doc')

    ctx.env.append_unique('USES_FTP', ['ftp_client', 'storage_h', 'gscsp', 'csp', 'util'])

    ctx.env.append_unique('FILES_FTP', ['src/*.c'])

    # Check for glob.h
    if not ctx.options.ftp_disable_glob and ctx.check_cc(header_name='glob.h', mandatory=False):
        ctx.env.append_unique('DEFINES_FTP', ['GS_FTP_USE_GLOB=1'])

    ctx.gs_add_doxygen()

    gs_gcc.gs_recurse(ctx)


def build(ctx):
    gs_gcc.gs_recurse(ctx)

    public_include = ctx.gs_include(name=APPNAME,
                                    includes=['include'])

    ctx.gs_objects(source=ctx.path.ant_glob(ctx.env.FILES_FTP),
                   target=APPNAME,
                   defines=ctx.env.DEFINES_FTP,
                   use=ctx.env.USES_FTP + [public_include])

    ctx.gs_shlib(source=ctx.path.ant_glob(ctx.env.FILES_FTP),
                 target=APPNAME,
                 defines=ctx.env.DEFINES_FTP,
                 gs_use_shlib=ctx.env.USES_FTP + [public_include])


def doc(ctx):
    gs_doc.library(ctx, keyvalues={
        'gs_prod_name': 'lib'+APPNAME,
        'gs_prod_desc': 'FTP server',
    })


def gs_dist(ctx):
    ctx.add_default_files(source_module=True)
    ctx.recurse(['lib/libftp_client'])
