/* Copyright (c) 2013 GomSpace A/S. All rights reserved. (AUTO GENERATED) */

#include <gs/adcs/param/host/gnc_common.h>
#include <gs/util/pgm.h>

const gs_param_table_row_t gs_adcs_gnc_common_table[] = {
    {.name = "inertia",       .addr = GS_ADCS_GNC_COMMON_INERTIA(0),                     .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  3, .flags = 0},
    {.name = "acs_init",      .addr = GS_ADCS_GNC_COMMON_ACS_INIT,                       .type = GS_PARAM_UINT8,   .size =   1, .array_size =  1, .flags = 0},
    {.name = "ads_init",      .addr = GS_ADCS_GNC_COMMON_ADS_INIT,                       .type = GS_PARAM_UINT8,   .size =   1, .array_size =  1, .flags = 0},
    {.name = "ephem_init",    .addr = GS_ADCS_GNC_COMMON_EPHEM_INIT,                     .type = GS_PARAM_UINT8,   .size =   1, .array_size =  1, .flags = 0},
    {.name = "sampletime",    .addr = GS_ADCS_GNC_COMMON_SAMPLETIME,                     .type = GS_PARAM_UINT16,  .size =   2, .array_size =  1, .flags = 0},
    {.name = "bdot_divider",  .addr = GS_ADCS_GNC_COMMON_BDOT_DIVIDER,                   .type = GS_PARAM_UINT16,  .size =   2, .array_size =  1, .flags = 0},
    {.name = "ephem_divider", .addr = GS_ADCS_GNC_COMMON_EPHEM_DIVIDER,                  .type = GS_PARAM_UINT16,  .size =   2, .array_size =  1, .flags = 0},
    {.name = "kf_divider",    .addr = GS_ADCS_GNC_COMMON_KF_DIVIDER,                     .type = GS_PARAM_UINT16,  .size =   2, .array_size =  1, .flags = 0},
    {.name = "ctrl_divider",  .addr = GS_ADCS_GNC_COMMON_CTRL_DIVIDER,                   .type = GS_PARAM_UINT16,  .size =   2, .array_size =  1, .flags = 0},
    {.name = "pwm_deadtime",  .addr = GS_ADCS_GNC_COMMON_PWM_DEADTIME,                   .type = GS_PARAM_UINT16,  .size =   2, .array_size =  1, .flags = 0},
    {.name = "tleline1",      .addr = GS_ADCS_GNC_COMMON_TLELINE1,                       .type = GS_PARAM_STRING,  .size =  70, .array_size =  1, .flags = 0},
    {.name = "tleline2",      .addr = GS_ADCS_GNC_COMMON_TLELINE2,                       .type = GS_PARAM_STRING,  .size =  70, .array_size =  1, .flags = 0},
    {.name = "teme2eci",      .addr = GS_ADCS_GNC_COMMON_TEME2ECI,                       .type = GS_PARAM_BOOL,    .size =   1, .array_size =  1, .flags = 0},
    {.name = "const_ctrl",    .addr = GS_ADCS_GNC_COMMON_CONST_CTRL(0),                  .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  3, .flags = 0},
    {.name = "bdot_to_ctrl",  .addr = GS_ADCS_GNC_COMMON_BDOT_TO_CTRL,                   .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = 0},
    {.name = "ctrl_to_bdot",  .addr = GS_ADCS_GNC_COMMON_CTRL_TO_BDOT,                   .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = 0},
    {.name = "bdot_tconst",   .addr = GS_ADCS_GNC_COMMON_BDOT_TCONST,                    .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = 0},
    {.name = "bdot_tconst2",  .addr = GS_ADCS_GNC_COMMON_BDOT_TCONST2,                   .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = 0},
    {.name = "bdot_tsep",     .addr = GS_ADCS_GNC_COMMON_BDOT_TSEP,                      .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = 0},
    {.name = "bdot_thres",    .addr = GS_ADCS_GNC_COMMON_BDOT_THRES(0),                  .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  3, .flags = 0},
    {.name = "bdot_t_limit",  .addr = GS_ADCS_GNC_COMMON_BDOT_T_LIMIT(0),                .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  3, .flags = 0},
    {.name = "bdot_axis",     .addr = GS_ADCS_GNC_COMMON_BDOT_AXIS,                      .type = GS_PARAM_UINT8,   .size =   1, .array_size =  1, .flags = 0},
    {.name = "bdot_bstreng",  .addr = GS_ADCS_GNC_COMMON_BDOT_BSTRENG,                   .type = GS_PARAM_UINT8,   .size =   1, .array_size =  1, .flags = 0},
    {.name = "bdot_sign",     .addr = GS_ADCS_GNC_COMMON_BDOT_SIGN,                      .type = GS_PARAM_INT8,    .size =   1, .array_size =  1, .flags = 0},
    {.name = "bdot_mag",      .addr = GS_ADCS_GNC_COMMON_BDOT_MAG,                       .type = GS_PARAM_UINT8,   .size =   1, .array_size =  1, .flags = 0},
    {.name = "bdot_rateref",  .addr = GS_ADCS_GNC_COMMON_BDOT_RATEREF(0),                .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  3, .flags = 0},
    {.name = "mtq_decay_t",   .addr = GS_ADCS_GNC_COMMON_MTQ_DECAY_T,                    .type = GS_PARAM_UINT8,   .size =   1, .array_size =  1, .flags = 0},
    {.name = "mag_sample_t",  .addr = GS_ADCS_GNC_COMMON_MAG_SAMPLE_T,                   .type = GS_PARAM_UINT8,   .size =   1, .array_size =  1, .flags = 0},
};

const gs_adcs_gnc_common_memory_t gs_adcs_gnc_common_default_values GS_PGM_OBJECT = {
    .inertia = {0.0925, 0.1143, 0.0392},
    .acs_init = 2,
    .ads_init = 0,
    .ephem_init = 0,
    .sampletime = 245,
    .bdot_divider = 1,
    .ephem_divider = 4,
    .kf_divider = 4,
    .ctrl_divider = 4,
    .pwm_deadtime = 30,
    .tleline1 = "1 41460U 16025E   16294.68301868  .00005868  00000-0  32510-3 0  9992",
    .tleline2 = "2 41460  98.2015 312.4255 0173064   8.5992 351.8080 15.02303438 26617",
    .teme2eci = true,
    .const_ctrl = {0.0, 0.0, 0.0},
    .bdot_to_ctrl = 1.2,
    .ctrl_to_bdot = 3.9,
    .bdot_tconst = 0.9,
    .bdot_tconst2 = 20.0,
    .bdot_tsep = 100.0,
    .bdot_thres = {0.1, 0.1, 0.1},
    .bdot_t_limit = {80.0, 80.0, 80.0},
    .bdot_axis = 2,
    .bdot_bstreng = 50,
    .bdot_sign = 1,
    .bdot_rateref = {0.0, 0.0, 0.0},
    .mtq_decay_t = 20,
    .mag_sample_t = 20,
};

