/* Copyright (c) 2013 GomSpace A/S. All rights reserved. (AUTO GENERATED) */

#include <gs/adcs/param/host/gnc_ads.h>
#include <gs/util/pgm.h>

const gs_param_table_row_t gs_adcs_gnc_ads_table[] = {
    {.name = "Q_quat",        .addr = GS_ADCS_GNC_ADS_Q_QUAT,                            .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = GS_PARAM_F_SHOW_SCIENTIFIC},
    {.name = "Q_rate",        .addr = GS_ADCS_GNC_ADS_Q_RATE,                            .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = GS_PARAM_F_SHOW_SCIENTIFIC},
    {.name = "Q_magbias",     .addr = GS_ADCS_GNC_ADS_Q_MAGBIAS,                         .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = GS_PARAM_F_SHOW_SCIENTIFIC},
    {.name = "Q_gyrobias",    .addr = GS_ADCS_GNC_ADS_Q_GYROBIAS,                        .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = GS_PARAM_F_SHOW_SCIENTIFIC},
    {.name = "Q_dtorque",     .addr = GS_ADCS_GNC_ADS_Q_DTORQUE,                         .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = GS_PARAM_F_SHOW_SCIENTIFIC},
    {.name = "R_css",         .addr = GS_ADCS_GNC_ADS_R_CSS,                             .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = GS_PARAM_F_SHOW_SCIENTIFIC},
    {.name = "R_mag",         .addr = GS_ADCS_GNC_ADS_R_MAG,                             .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = GS_PARAM_F_SHOW_SCIENTIFIC},
    {.name = "R_gyro",        .addr = GS_ADCS_GNC_ADS_R_GYRO,                            .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = GS_PARAM_F_SHOW_SCIENTIFIC},
    {.name = "R_fss",         .addr = GS_ADCS_GNC_ADS_R_FSS,                             .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = GS_PARAM_F_SHOW_SCIENTIFIC},
    {.name = "R_st",          .addr = GS_ADCS_GNC_ADS_R_ST,                              .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = GS_PARAM_F_SHOW_SCIENTIFIC},
    {.name = "R_htpa",        .addr = GS_ADCS_GNC_ADS_R_HTPA,                            .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = GS_PARAM_F_SHOW_SCIENTIFIC},
    {.name = "P_quat",        .addr = GS_ADCS_GNC_ADS_P_QUAT,                            .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = GS_PARAM_F_SHOW_SCIENTIFIC},
    {.name = "P_rate",        .addr = GS_ADCS_GNC_ADS_P_RATE,                            .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = GS_PARAM_F_SHOW_SCIENTIFIC},
    {.name = "P_magbias",     .addr = GS_ADCS_GNC_ADS_P_MAGBIAS,                         .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = GS_PARAM_F_SHOW_SCIENTIFIC},
    {.name = "P_gyrobias",    .addr = GS_ADCS_GNC_ADS_P_GYROBIAS,                        .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = GS_PARAM_F_SHOW_SCIENTIFIC},
    {.name = "P_dtorque",     .addr = GS_ADCS_GNC_ADS_P_DTORQUE,                         .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = GS_PARAM_F_SHOW_SCIENTIFIC},
    {.name = "no_chng_dsbl",  .addr = GS_ADCS_GNC_ADS_NO_CHNG_DSBL,                      .type = GS_PARAM_BOOL,    .size =   1, .array_size =  1, .flags = 0},
    {.name = "en_ctrltorque", .addr = GS_ADCS_GNC_ADS_EN_CTRLTORQUE,                     .type = GS_PARAM_BOOL,    .size =   1, .array_size =  1, .flags = 0},
    {.name = "enable_fss",    .addr = GS_ADCS_GNC_ADS_ENABLE_FSS,                        .type = GS_PARAM_UINT8,   .size =   1, .array_size =  1, .flags = 0},
    {.name = "enable_st",     .addr = GS_ADCS_GNC_ADS_ENABLE_ST,                         .type = GS_PARAM_BOOL,    .size =   1, .array_size =  1, .flags = 0},
    {.name = "enable_htpa",   .addr = GS_ADCS_GNC_ADS_ENABLE_HTPA,                       .type = GS_PARAM_BOOL,    .size =   1, .array_size =  1, .flags = 0},
    {.name = "enable_maxcur", .addr = GS_ADCS_GNC_ADS_ENABLE_MAXCUR,                     .type = GS_PARAM_BOOL,    .size =   1, .array_size =  1, .flags = 0},
    {.name = "en_norm_mag",   .addr = GS_ADCS_GNC_ADS_EN_NORM_MAG,                       .type = GS_PARAM_BOOL,    .size =   1, .array_size =  1, .flags = 0},
    {.name = "en_norm_bias",  .addr = GS_ADCS_GNC_ADS_EN_NORM_BIAS,                      .type = GS_PARAM_BOOL,    .size =   1, .array_size =  1, .flags = 0},
    {.name = "mag_choice",    .addr = GS_ADCS_GNC_ADS_MAG_CHOICE,                        .type = GS_PARAM_UINT8,   .size =   1, .array_size =  1, .flags = 0},
    {.name = "gyro_choice",   .addr = GS_ADCS_GNC_ADS_GYRO_CHOICE,                       .type = GS_PARAM_UINT8,   .size =   1, .array_size =  1, .flags = 0},
    {.name = "int_choice",    .addr = GS_ADCS_GNC_ADS_INT_CHOICE,                        .type = GS_PARAM_UINT8,   .size =   1, .array_size =  1, .flags = 0},
    {.name = "kf_choice",     .addr = GS_ADCS_GNC_ADS_KF_CHOICE,                         .type = GS_PARAM_UINT8,   .size =   1, .array_size =  1, .flags = 0},
    {.name = "M_bias",        .addr = GS_ADCS_GNC_ADS_M_BIAS(0),                         .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  3, .flags = 0},
    {.name = "min_angle",     .addr = GS_ADCS_GNC_ADS_MIN_ANGLE,                         .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = 0},
    {.name = "htpa_err",      .addr = GS_ADCS_GNC_ADS_HTPA_ERR,                          .type = GS_PARAM_FLOAT,   .size =   4, .array_size =  1, .flags = 0},
    {.name = "st_override",   .addr = GS_ADCS_GNC_ADS_ST_OVERRIDE,                       .type = GS_PARAM_BOOL,    .size =   1, .array_size =  1, .flags = 0},
};

const gs_adcs_gnc_ads_memory_t gs_adcs_gnc_ads_default_values GS_PGM_OBJECT = {
    .Q_quat = 2e-07,
    .Q_rate = 1e-09,
    .Q_magbias = 1e-10,
    .Q_gyrobias = 9e-11,
    .Q_dtorque = 1e-08,
    .R_css = 0.1,
    .R_mag = 5.0,
    .R_gyro = 0.0001,
    .R_fss = 0.02,
    .R_st = 1e-11,
    .R_htpa = 0.1,
    .P_quat = 0.001,
    .P_rate = 0.0001,
    .P_magbias = 1e-09,
    .P_gyrobias = 1e-06,
    .P_dtorque = 1e-09,
    .no_chng_dsbl = false,
    .en_ctrltorque = true,
    .enable_fss = 1,
    .enable_st = false,
    .enable_htpa = false,
    .enable_maxcur = false,
    .en_norm_mag = false,
    .en_norm_bias = false,
    .mag_choice = 0,
    .gyro_choice = 0,
    .int_choice = 0,
    .kf_choice = 0,
    .M_bias = {0.02, 0.02, 0.02},
    .min_angle = 0.0,
    .htpa_err = 10.0,
    .st_override = false,
};

