#!/usr/bin/env python
# encoding: utf-8
# Copyright (c) 2013-2017 GomSpace A/S. All rights reserved.

import os
import time
import gs_gcc
import gs_doc

APPNAME = 'adcs_client'


def options(ctx):
    ctx.recurse(gs_gcc.get_modules(ctx))
    ctx.load('gs_gcc')


def configure(ctx):
    ctx.recurse(gs_gcc.get_modules(ctx))

    ctx.load('gs_gcc')


def build(ctx):
    ctx.recurse(gs_gcc.get_modules(ctx))

    ctx.gs_call_handler(handler='param_gen_4_3', name=APPNAME, prefix='adcs',
                        update_source=True,
                        generate_client=True,
                        generate_host=True,
                        generate_rst=True)

    public_include = ctx.gs_include(includes=['include'], name=APPNAME)
    ctx.gs_objects(source=ctx.path.ant_glob('src/**/*.c', excl='checkout_adcs.c'),
                   target=APPNAME,
                   includes=['include'],
                   use=['csp', 'gosh', 'param_client', 'util', public_include])

    ctx.gs_shlib(source=ctx.path.ant_glob('src/*.c', excl='checkout_adcs.c'),
                 target=APPNAME,
                 includes=['include'],
                 gs_use_shlib=['csp', 'gosh', 'param_client', 'util'],
                 use=[public_include])

    if ctx.env.ADCS_ENABLE_BINDINGS:
        ctx.gs_python_bindings(source=ctx.path.ant_glob('adcs/bindings/python/*.c'),
                               target=APPNAME,
                               gs_use_shlib=[APPNAME, 'csp', 'gosh', 'param_client', 'util', public_include])


def gs_dist(ctx):
    ctx.add_default_files(source_module=True)
