#!/usr/bin/env python
# Copyright (c) 2013-2017 GomSpace A/S. All rights reserved.
# encoding: utf-8

import gs_gcc

APPNAME = 'p60-dock_client'


def options(ctx):
    gr = ctx.add_option_group('NanoPower-P60 Dock client options')
    gr.add_option('--disable-p60-dock-cmd', action='store_true', help='Disable client cmd code for NanoPower-P60 Dock')


def configure(ctx):
    ctx.env.append_unique('FILES_P60_DOCK_CLIENT', ['src/p60dock_client.c'])
    ctx.env.append_unique('FILES_P60_DOCK_CLIENT', ['src/p60dock_confcal.c'])
    if not ctx.options.disable_p60_dock_cmd:
        ctx.env.append_unique('FILES_P60_DOCK_CLIENT', ['src/p60dock_cmd.c'])


def build(ctx):
    gs_gcc.gs_call_handler(ctx, handler='param_gen_4_3', name=APPNAME, prefix='p60-dock',
                           generate_rst=True)

    public_include = APPNAME + '_h'
    ctx(export_includes=['include', 'include/gs/p60-dock/param'], name=public_include)

    ctx.objects(source=ctx.path.ant_glob(ctx.env.FILES_P60_DOCK_CLIENT),
                target=APPNAME,
                use=['csp', 'gosh', 'param', 'param_client', 'p60_client', public_include])


def gs_dist(ctx):
    ctx.add_default_files(source_module=True)
