#ifndef USER_BOARD_H_
#define USER_BOARD_H_

#include "compiler.h"

#define FOSC32				AVR32_SCIF_OSC32_FREQUENCY
#define OSC32_STARTUP			AVR32_SCIF_OSCCTRL32_STARTUP_8192_RCOSC
#define FOSC0				16000000
#define OSC0_STARTUP			AVR32_SCIF_OSCCTRL0_STARTUP_2048_RCOSC

#define BOARD_OSC0_HZ			16000000
#define BOARD_OSC0_STARTUP_US		2000
#define BOARD_OSC0_IS_XTAL		true
#define BOARD_OSC32_HZ			32768
#define BOARD_OSC32_STARTUP_US		71000
#define BOARD_OSC32_IS_XTAL		false

#define SDRAM_PART_HDR			"mt48lc16m16a2tg7e/mt48lc16m16a2tg7e.h"
#define SDRAM_DBW			16

#define SD_MMC_SPI_MEM_CNT          1
//#define SD_MMC_0_CD_GPIO          AVR32_PIN_PA28
//#define SD_MMC_0_CD_DETECT_VALUE  1
//#define SD_MMC_0_WP_GPIO          AVR32_PIN_PD30
//#define SD_MMC_0_WP_DETECT_VALUE  0
#define SD_MMC_SPI_0_CS             0
#define SD_MMC_SPI_0_CS_PIN         AVR32_PIN_PA27

//#define SD_MMC_CARD_DETECT_PIN    SD_MMC_0_CD_GPIO
//#define SD_MMC_WRITE_PROTECT_PIN  SD_MMC_0_WP_GPIO
//#define SD_MMC_SPI_NPCS           SD_MMC_SPI_0_CS

#define SD_MMC_SPI                  (&AVR32_SPI1)
#define SD_MMC_SPI_SCK_PIN          AVR32_SPI1_SCK_0_1_PIN
#define SD_MMC_SPI_SCK_FUNCTION     AVR32_SPI1_SCK_0_1_FUNCTION
#define SD_MMC_SPI_MISO_PIN         AVR32_SPI1_MISO_0_1_PIN
#define SD_MMC_SPI_MISO_FUNCTION    AVR32_SPI1_MISO_0_1_FUNCTION
#define SD_MMC_SPI_MOSI_PIN         AVR32_SPI1_MOSI_0_1_PIN
#define SD_MMC_SPI_MOSI_FUNCTION    AVR32_SPI1_MOSI_0_1_FUNCTION
//#define SD_MMC_SPI_NPCS_PIN       AVR32_SPI1_NPCS_0_2_PIN
//#define SD_MMC_SPI_NPCS_FUNCTION  AVR32_SPI1_NPCS_0_2_FUNCTION

#define CONF_USART      			USART
#define CONF_BAUDRATE   			500000
#define CONF_CHARLENGTH 			8
#define CONF_PARITY     			USART_NO_PARITY
#define CONF_STOPBITS   			USART_1_STOPBIT

#define LM70_SPI					(&AVR32_SPI1)
#define LM70_SPI_CS					2
#define LM70_SPI_CS_TEMP1_PIN		        AVR32_PIN_PC00
#define LM70_SPI_CS_TEMP2_PIN		        AVR32_PIN_PB23

#define FM33256_SPI					(&AVR32_SPI1)
#define FM33256_SPI_CS				3

#define SPN_FL512S_CS0				0
#define SPN_FL512S_CS1				1
#define SPN_Fl512S_SPI				(&AVR32_SPI1)

#define PWR_GSSB_PIN                AVR32_PIN_PA28
#define PWR_SD_PIN                  AVR32_PIN_PA29
#define PWR_GSSB2_PIN               AVR32_PIN_PB25
#define PWR_PWM_PIN                 AVR32_PIN_PA21

#endif  // USER_BOARD_H_
