#!/usr/bin/env python
# encoding: utf-8
# Copyright (c) 2013-2017 GomSpace A/S. All rights reserved.

import gs_gcc
import gs_doc
import gs_dist
from waflib.Build import BuildContext

APPNAME = 'thirdparty'


def options(ctx):
    ctx.load("gs_gcc")
    gs_gcc.gs_recurse(ctx)


def configure(ctx):
    ctx.load("gs_gcc gs_doc")

    ctx.env.append_unique('FILES_THIRDPARTY', ['src/htpa/**/*.c',
                                               'src/fram/**/*.c',
                                               'src/tmp100/**/*.c',
                                               'src/tps382x/**/*.c',
                                               'src/ina226/**/*.c',
                                               'src/rm3100/**/*.c',
                                               'src/lm71/**/*.c',
                                               'src/isis_ants/**/*.c'])

    if not ctx.gs_is_linux():
        ctx.env.append_unique('FILES_THIRDPARTY', ['src/novatel_gnss/**/*.c',
                                                   'src/af_wheel/**/*.c',
                                                   'src/flash/**/*.c',
                                                   'src/hyp_st200/**/*.c'])

    ctx.gs_add_doxygen(exclude=['*/include/gs/thirdparty/novatel_gnss/*',
                                '*/include/gs/thirdparty/htpa/*'])

    gs_gcc.gs_recurse(ctx)


def build(ctx):
    gs_gcc.gs_recurse(ctx)

    public_include = ctx.gs_include(includes=['include'], name=APPNAME)
    use = ['embed', 'embed_h', 'util', public_include]

    ctx.gs_objects(source=ctx.path.ant_glob(ctx.env.FILES_THIRDPARTY),
                   target=APPNAME,
                   use=use)

    ctx.gs_shlib(source=ctx.path.ant_glob(ctx.env.FILES_THIRDPARTY),
                 target=APPNAME,
                 gs_use_shlib=use)

    ctx.gs_python_bindings(source=ctx.path.ant_glob('src/bindings/python/*.c'),
                           target=APPNAME,
                           gs_use_shlib=use + [APPNAME],
                           package='libthirdparty')


def doc(ctx):
    gs_doc.library(ctx, keyvalues={
        'gs_prod_name': 'lib'+APPNAME,
        'gs_prod_desc': 'Thirdparty drivers',
        'gs_watermark_text': 'INTERNAL',
    })


class Doc(BuildContext):
    cmd = fun = 'doc'


def gs_dist(ctx):
    ctx.add_default_files(source_module=True)
