#!/usr/bin/env python
# encoding: utf-8
# Copyright (c) 2013-2018 GomSpace A/S. All rights reserved.

import os
import gs_gcc

APPNAME = 'rgosh_client'


def options(ctx):
    ctx.load('gs_gcc')
    gs_gcc.gs_recurse(ctx)


def configure(ctx):
    ctx.load('gs_gcc')
    ctx.gs_add_doxygen(exclude=['*/include/gs/rgosh/internal/*'])
    gs_gcc.gs_recurse(ctx)


def build(ctx):
    gs_gcc.gs_recurse(ctx)

    ctx.gs_call_handler(handler='nano_proto_gen_3_9',
                        source=ctx.path.ant_glob(['conf/proto/*.proto']),
                        name='RGOSH_CLIENT_PROTO')

    public_include = ctx.gs_include(name=APPNAME, includes=['include', 'conf'])
    use = ['nanopb', 'gscsp', 'util', public_include]
    source = ctx.path.ant_glob(['src/*.c', 'src/cmd/*.c', 'conf/proto/*.c'])

    ctx.gs_objects(source=source,
                   target=APPNAME,
                   use=use)

    ctx.gs_shlib(source=source,
                 target=APPNAME,
                 gs_use_shlib=use)

    ctx.gs_python_bindings(source=ctx.path.ant_glob(['src/bindings/python/*.c']),
                           target=APPNAME,
                           gs_use_shlib=use + [APPNAME],
                           package='librgosh_client')


def gs_dist(ctx):
    ctx.add_default_files(source_module=True)
    ctx.add_files(ctx.path.ant_glob('conf/**'))
