#!/usr/bin/env python
# encoding: utf-8
# Copyright (c) 2013-2018 GomSpace A/S. All rights reserved.

import os
import gs_gcc
import gs_doc
from waflib.Build import BuildContext

APPNAME = 'rgosh'


def options(ctx):
    ctx.load('gs_gcc gs_doc')
    gs_gcc.gs_recurse(ctx)


def configure(ctx):
    ctx.load('gs_gcc gs_doc')
    ctx.gs_add_doxygen()
    gs_gcc.gs_recurse(ctx)


def build(ctx):
    gs_gcc.gs_recurse(ctx)

    public_include = ctx.gs_include(name=APPNAME, includes=['include'])
    use = ['rgosh_client', 'nanopb', 'gscsp', 'util', public_include]
    source = ctx.path.ant_glob(['src/*.c'])

    ctx.gs_objects(source=source,
                   target=APPNAME,
                   use=use)

    ctx.gs_shlib(source=source,
                 target=APPNAME,
                 gs_use_shlib=use)


def doc(ctx):
    gs_doc.library(ctx, keyvalues={
        'gs_prod_name': 'lib'+APPNAME,
        'gs_prod_desc': 'Remote GOSH',
        'gs_watermark_text': 'INTERNAL',
    })


class Doc(BuildContext):
    cmd = fun = 'doc'


def gs_dist(ctx):
    ctx.add_default_files(source_module=True)
    ctx.recurse(['lib/librgosh_client'])
