#!/usr/bin/env python
# encoding: utf-8
# Copyright (c) 2013-2017 GomSpace A/S. All rights reserved.

import gs_gcc
import gs_doc
import gs_dist
from waflib.Build import BuildContext

APPNAME = 'hk'


def options(ctx):
    ctx.load('gs_gcc gs_doc')
    gs_gcc.gs_recurse(ctx)


def configure(ctx):
    ctx.load('gs_gcc gs_doc')

    ctx.env.append_unique('USES_HK', ['hk_client', 'param', 'gscsp', 'util', 'storage_h', 'json'])

    ctx.env.append_unique('FILES_HK', ['src/*/*.c'])

    ctx.gs_add_doxygen(exclude=['*/include/gs/hk/internal/*'])

    gs_gcc.gs_recurse(ctx)


def build(ctx):
    gs_gcc.gs_recurse(ctx)

    ctx.gs_call_handler(handler='param_gen_4_3', name=APPNAME, prefix='hk',
                        input=['lib/libhk_client/conf/tables/hkcfg.json'],
                        generate_host=True)

    ctx.gs_call_handler(handler='command_gen_4_0', name=APPNAME,
                        generate_src=True,
                        generate_rst_sections=True,
                        generate_rsti_table=True)

    public_include = ctx.gs_include(name=APPNAME, includes=['include'])

    ctx.gs_objects(source=ctx.path.ant_glob(ctx.env.FILES_HK),
                   target=APPNAME,
                   includes=['src'],
                   defines=ctx.env.DEFINES_HK,
                   use=ctx.env.USES_HK + [public_include])

    ctx.gs_shlib(source=ctx.path.ant_glob(ctx.env.FILES_HK),
                 target=APPNAME,
                 includes=['src'],
                 defines=ctx.env.DEFINES_HK,
                 gs_use_shlib=ctx.env.USES_HK,
                 use=[public_include])

    ctx.gs_python_bindings(source=ctx.path.ant_glob('src/bindings/python/*.c'),
                           target=APPNAME,
                           gs_use_shlib=ctx.env.USES_HK + [APPNAME],
                           use=[public_include],
                           package='libhk')


def doc(ctx):
    gs_doc.library(ctx, keyvalues={
        'gs_prod_name': 'lib' + APPNAME,
        'gs_prod_desc': 'Housekeeping Library',
    })


class Doc(BuildContext):
    cmd = fun = 'doc'


def gs_dist(ctx):
    ctx.add_default_files(source_module=True)
    ctx.recurse(['lib/libhk_client'])
